### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by looeee** [threejs/lwoloader-test-models#13]
Just noticed that a `debug` parameter got added somewhere along the way, I must have missed that. @sciecode can you explain what this does?

https://github.com/threejs/lwoloader-test-models/blob/ef60412bd98f22660d8e888c19c3611094d31b86/src/Loader.js#L12

**Comment by sciecode** [comment]
Sure thing. This was included on the very first commit I made to the repo.
I created this debugger to help me understand the FORMs and CHUNKs for LWO files. 
When enabled, it logs the IFF hierarchy on the console. It also reports which blocks are currently being skipped. This is how it looks:

![image](https://user-images.githubusercontent.com/3927951/56573887-6971a280-6598-11e9-8ba1-003c69a41f4d.png)

I've kept this because it could be useful for other people working on the parser. But in reality I don't feel like this should be pushed to threejs:master main repo.

I was thinking about excluding it from final builds, but I'm unsure on how to do that properly. If you have any suggestions, I'm all ears.

**Comment by looeee** [comment]
OK, that's useful. But it's best not to make this a user accessible feature. Could we do something similar to the `printBuffer` function where you can just un-comment a line or two to log all the things that get skipped? 

How about something like this in the FBXLoader  - l left this line in since it's easy to just comment it out for production:


https://github.com/mrdoob/three.js/blob/c2adfa442611818973843654ec2a57fd01ef91e3/examples/js/loaders/FBXLoader.js#L119

> I was thinking about excluding it from final builds, but I'm unsure on how to do that properly.

Hmm, I'm not aware of any way of doing that. But I'm not sure that's a good path to go down either, the final build should just be a compiled version of what's in the source.

**Comment by sciecode** [comment]
> Could we do something similar to the printBuffer function where you can just un-comment a line or two to log all the things that get skipped?

We can remove the parameter from the Loader itself and just keep it as local thing inside IFFparser. 
The logic used to create the hierarchy-viewer will still be mixed inside the blocks/forms parsing functions, but we can quickly activate or deactivate it with a simple comment/un-comment. 

I'll get a new PR ready in a few minutes with these changes.

> Hmm, I'm not aware of any way of doing that. But I'm not sure that's a good path to go down either, the final build should just be a compiled version of what's in the source.

Thinking about it now, you are probably right.
